import clsx from 'clsx';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  variable: '--font-quicksand',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(quicksand.variable, 'antialiased')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
